var rule = {
  title: 'javeng',
  host: 'https://javeng.com/',
  //homeUrl:'https://123av.ws/zh',
  url: '/fyclass/page/fypage/',
  detailUrl:'*',
  searchUrl: '/zh/vod/search/page/fypage/wd/**.html',
  searchable: 2,
  headers: {'User-Agent': 'MOBILE_UA'},
  hikerListCol: "movie_2",
  hikerClassListCol: "movie_2",
  timeout: 5000,
  class_name: '最近更新&热门',
  class_url: 'jav-eng-sub&dm9/trending',
  play_parse: true,
  lazy: '$js.toString(() => {let html = JSON.parse(request(input).match(/r player_.*?=(.*?)</)[1]);let link = html.url;input = {parse: 0, url: link, header: rule.headers};})',
  tab_rename: {'道长在线': '在线浏览'},
  double: true,
  推荐: '.row-space7;.mb15;h2.rows-2&&Text;img&&src;.ico-right&&Text;a&&href;.ico-left&&Text',
  一级: '#archive-content&&article;h3&&a&&Text;img&&src;.duration&&Text;h3&&a&&href;.duration&&Text',
  二级:'*',
  搜索: '.row-space7 .mb15;h2.rows-2&&Text;img&&src;.ico-right&&Text;a&&href;.ico-left&&Text',
}